# Site settings
title: 'QIAILIN-HOME'  # Your Title
tagline: '柔弱、无欲，顺乎自然，但却具有强大的生命力'  # A brief tagline for your site
sidebar_image: /images/cover.jpg

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: ""


# Site settings
name:           qiailin
email:          qiailin@yeah.net
uri:            qiailin.github.io
github:         qiailin
twitter:        qiailin
facebook:       qiailin
linkedin:       qiailin